# Generated by Django 5.0.6 on 2024-05-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='стоимость'),
        ),
    ]
